[package]
name = "ocaml-interop"
version = "0.1.11"
authors = ["Bruno Deferrari <utizoc@gmail.com>"]
license = "MIT"
description = "Utilities for Rust and OCaml interoperability"
homepage = "http://github.com/simplestaking/ocaml-interop"
repository = "http://github.com/simplestaking/ocaml-interop"
