[package]
name = "ocaml-interop"
version = "0.2.0"
authors = ["Bruno Deferrari <utizoc@gmail.com>"]
license = "MIT"
description = "Utilities for Rust and OCaml interoperability"
homepage = "http://github.com/simplestaking/ocaml-interop"
repository = "http://github.com/simplestaking/ocaml-interop"
keywords = ["ocaml", "rust", "ffi", "interop"]
exclude = [
    ".github/*",
]