name: Clippy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: OCaml/Opam cache
        id: ocaml-interop-opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: clippy
      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.11.1
      - name: Set Opam env
        run: opam env >> $GITHUB_ENV
      - name: Add Opam switch to PATH
        run: opam var bin >> $GITHUB_PATH
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
